spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: shopping-cart-route
          uri: lb://shopping-cart
          predicates:
            - Path=/shopping-cart/**
          filters:
            - PrefixPath=/api/v1

        - id: shopping-store-route
          uri: lb://shopping-store
          predicates:
            - Path=/shopping-store/**
          filters:
            - PrefixPath=/api/v1
            - name: Retry
              args:
                retries: 1
                statuses: NOT_FOUND
                methods: GET

        - id: warehouse-route
          uri: lb://warehouse
          predicates:
            - Path=/warehouse/**
          filters:
            - PrefixPath=/api/v1

        - id: order-route
          uri: lb://order
          predicates:
            - Path=/order/**
          filters:
            - PrefixPath=/api/v1

        - id: payment-route
          uri: lb://payment
          predicates:
            - Path=/payment/**
          filters:
            - PrefixPath=/api/v1

        - id: delivery-route
          uri: lb://delivery
          predicates:
            - Path=/delivery/**
          filters:
            - PrefixPath=/api/v1

server:
  port: 8080

logging:
  level:
    ru.yandex.practicum: INFO
